# Generated by Django 4.1.13 on 2023-11-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ourbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lector',
            new_name='Reader',
        ),
    ]
