# Generated by Django 4.1.13 on 2023-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ourbooks', '0002_rename_lector_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='groups',
            field=models.ManyToManyField(related_name='reader_groups', to='auth.group'),
        ),
    ]
