# Generated by Django 4.2.7 on 2023-11-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourbooks', '0003_alter_reader_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('publication_year', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=250)),
                ('author_first_name', models.CharField(max_length=40)),
                ('author_last_name', models.CharField(max_length=40)),
                ('editorial_mail', models.CharField(max_length=75)),
            ],
        ),
    ]
