# Generated by Django 4.1.13 on 2023-11-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ourbooks', '__first__'),
        ('Editoriales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_purchase', models.BooleanField(default=True)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editoriales.books')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourbooks.reader')),
            ],
            options={
                'unique_together': {('book_id', 'reader_id', 'is_purchase')},
            },
        ),
    ]
