# Generated by Django 4.1.13 on 2023-11-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourbooks', '__first__'),
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('reader_id',)},
        ),
    ]
