# Generated by Django 4.1.13 on 2023-11-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editoriales', '__first__'),
        ('ourbooks', '__first__'),
        ('readers', '0002_alter_ownership_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('reader_id', 'book_id')},
        ),
    ]
