# Generated by Django 4.1.13 on 2023-11-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_alter_ownership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='book_owner_id',
            field=models.IntegerField(default=None),
        ),
    ]
