# Generated by Django 4.1.13 on 2023-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0007_alter_ownership_book_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='book_owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
