# Generated by Django 4.1.13 on 2023-11-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0010_alter_ownershare_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershare',
            name='share',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='readers.share'),
        ),
    ]
